config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resource :dashboard, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  #get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  resources :team, only: [:index]
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :lessons, only: [:show]

  namespace :instructor do
    resources :lessons, only: [:update]
    resources :sections, only: [:update] do
      resources :lessons, only: [:create]
    end
      resources :courses, only: [:new, :create, :show] do
        resources :sections, only: [:create]  
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all    
  end

  def show
    @course = Course.find(params[:id])    
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only:[:show]
  

  def new
    @course = Course.new  
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
    redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
     @section = Section.new
     @lesson = Lesson.new
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render plain: "Unauthorized", status: :unauthorized 
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
    
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image) 
  end

end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
  before_action :require_authorized_for_current_lesson, only: [:update]
  

  def create
    
    @lesson = current_section.lessons.create(lesson_params)
    redirect_to instructor_course_path(current_section.course)
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render plain: 'updated!'
    
  end

  private

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
    
  end


  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

  

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def update
    @current_section.update_attributes(section_params)
    render plain: 'updated!'
  end

  private

  def current_section
    @current_section ||= Section.find(params[:id])
    
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render plain: 'Unauthorized', status: :unauthorized
    end
    
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      return render plain: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_course  
  def current_course
    @current_course ||= Course.find(params[:course_id])
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
    
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <br />
    <%= f.input :image %>
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
    <% end %>
    <br />

</div>

app/views/instructor/courses/show.html.erb
<script type="text/javascript">

  

  $(function(){

     $('.new-lesson-button').click(function(){
      var lessonUrl = $(event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    });



    $('.lessons').sortable({
      update: function(event, ui){
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json', 
          data: {lesson: {row_order_position: ui.item.index() }}
        });
      }
    }); 

  });

  $(function(){
    $('.sections').sortable({
      update: function(event, ui){
          $.ajax({
              type: 'PUT',
              url: ui.item.data('update-url'),
              dataType: 'json', 
              data: {section: {row_order_position: ui.item.index() }}
            });
          }
        });
          
  });
        

</script>

<br />
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <%= image_tag current_course.image, class: 'img-fluid' %>
  <br />
  <br />
  <%= link_to 'Preview as Student...', course_path(current_course), class: 'btn btn-warning float-right' %>
  <br class="clr" />
  <div class="text-center">
    <!-- Button trigger modal Section -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newSectionModal">
        Add New Section
      </button>    
  </div>

  <ul class="sections">
    <% current_course.sections.rank(:row_order).each do |section| %>
      <li  data-update-url="<%= instructor_section_path(section) %>" class="section-li">
        <div class="header">
        <i class="fa fa-ellipsis-v"></i>
        <%= section.title %>
      </div>

        <!-- Button trigger modal Lesson-->
        <button type="button" class="btn btn-primary btn-lg float-right new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
          New Lesson...
        </button>        
          <br class="clr" />
          <br class="clr">
        <ul class="lessons">
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <li data-update-url="<%= instructor_lesson_path(lesson) %>">
              <div class="row">
                <div class="col-1">
                  <br />
                  <i class="fa fa-ellipsis-v"></i>
                </div>
              <div class="col-11 text-center">
                <p>
                  <b><%= lesson.title %></b>
                </p>
                <p>
                  <%= lesson.subtitle %>
                </p>
              </div>
            </div>
              <br class="clr" />
            </li>
            <% end %>
        </ul>
        
        <br class="clr" />
      </li>
    <% end %>
  </ul>
</div>



<!-- Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newSectionModal">Add a new Section</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
      <div class="modal-body">
        <%= f.input :title %>
        <br />
        <br />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add a section", class: 'btn btn-primary' %>
        <br />
      </div>
      <% end %>
    </div>
  </div>
</div>



<!-- Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newLessonModal">Add a New Lesson</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for @lesson, url: "#" , html: {id: 'newLessonForm'} do |f| %>

      <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :video %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add the lesson", class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>